<a href="https://colab.research.google.com/github/Maxzeno/machine-learning/blob/main/00_pytorch_fundamentals_video.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [25]:
import torch
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [26]:
scalar = torch.tensor(3, dtype=torch.int8)
# .item() returns the python data type for a scalar eg. tensor(5) return 5 
scalar.dtype

torch.int8

In [27]:
vector = torch.tensor([5, 6])
(vector*2).sum()
vector.ndim, vector.shape

(1, torch.Size([2]))

In [28]:
MATRIX = torch.tensor([[5, 2],
                       [7, 9]])
MATRIX
MATRIX[0]

tensor([5, 2])

In [29]:
TENSOR = torch.tensor([[[[2, 8, 6],
                        [4, 5, 6],
                        [8, 9, 3]]]])
TENSOR.shape

torch.Size([1, 1, 3, 3])

###Random Tensors

In [30]:
random_tensor = torch.rand(size=(5, 9))
random_tensor

tensor([[0.3955, 0.5670, 0.4280, 0.4308, 0.6680, 0.0104, 0.2018, 0.6606, 0.2057],
        [0.4373, 0.9568, 0.1236, 0.4189, 0.4455, 0.5950, 0.7262, 0.2344, 0.6919],
        [0.4120, 0.8440, 0.9889, 0.4637, 0.1260, 0.6415, 0.2094, 0.8010, 0.2828],
        [0.9886, 0.9565, 0.8205, 0.9341, 0.3787, 0.1898, 0.8851, 0.2545, 0.4857],
        [0.7332, 0.7734, 0.0121, 0.2701, 0.6939, 0.4663, 0.6038, 0.2779, 0.2309]])

In [31]:
random_tensor[0:3, 1:5]

tensor([[0.5670, 0.4280, 0.4308, 0.6680],
        [0.9568, 0.1236, 0.4189, 0.4455],
        [0.8440, 0.9889, 0.4637, 0.1260]])

In [32]:
zero = torch.zeros(3, 4)
zero * random_tensor[0:3, 1:5]


tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [33]:
arange = torch.arange(1, 50, 2)
arange

tensor([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19, 21, 23, 25, 27, 29, 31, 33, 35,
        37, 39, 41, 43, 45, 47, 49])

In [34]:
# creating tensors like
torch.zeros(arange.shape, dtype=arange.dtype)

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0])

In [35]:
torch.ones_like(input=arange)

tensor([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
        1])

In [36]:
torch.full_like(input=arange, fill_value=1.2, dtype=torch.float64)

tensor([1.2000, 1.2000, 1.2000, 1.2000, 1.2000, 1.2000, 1.2000, 1.2000, 1.2000,
        1.2000, 1.2000, 1.2000, 1.2000, 1.2000, 1.2000, 1.2000, 1.2000, 1.2000,
        1.2000, 1.2000, 1.2000, 1.2000, 1.2000, 1.2000, 1.2000],
       dtype=torch.float64)

In [37]:
f = torch.tensor([[1, 2], [8, 9], [5, 8]], dtype=torch.int64)

t = torch.tensor([[5, 5], [6, 2]], dtype=torch.int64)

In [38]:
torch.matmul(f, t)

tensor([[17,  9],
        [94, 58],
        [73, 41]])

In [39]:
ar = torch.arange(1, 7)
ar = ar.reshape(3, 2)

In [40]:
ar2 = torch.arange(7, 13)
ar2 = ar2.reshape(2, 3).T

In [41]:
torch.mm(ar, ar2.T)

tensor([[ 27,  30,  33],
        [ 61,  68,  75],
        [ 95, 106, 117]])

In [42]:
ar.type(torch.float32).mean()

tensor(3.5000)

In [43]:
(ar.argmin() == 0).to(torch.int8)

tensor(1, dtype=torch.int8)

In [44]:
x = torch.arange(1., 11.)
x.shape, x.ndim, x
rex1 = x.reshape(1, 10)
rex1.shape, rex1.ndim, rex1
x.reshape(10)

tensor([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [45]:
z = x.view(1, 10)
z[:, 0:2] = torch.tensor([5, 60])
x, z

(tensor([ 5., 60.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.]),
 tensor([[ 5., 60.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.]]))

In [46]:
x_stack = torch.stack([x], dim=0)
x_stack.shape, x_stack.ndim, x_stack

(torch.Size([1, 10]),
 2,
 tensor([[ 5., 60.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.]]))

In [47]:
sq = torch.squeeze(rex1)
sq, rex1
unsq = torch.unsqueeze(rex1, dim=1)
unsq.shape

torch.Size([1, 1, 10])

In [48]:
# ar.permute()
arr = torch.stack([ar], dim=0)
arr.shape
arp = arr.permute(2, 1, 0)
arp[0, 0, 0] = 500

In [49]:
arr, arp

(tensor([[[500,   2],
          [  3,   4],
          [  5,   6]]]),
 tensor([[[500],
          [  3],
          [  5]],
 
         [[  2],
          [  4],
          [  6]]]))

In [50]:
a = torch.arange(1, 10).reshape(1, 3, 3)
a[0, :, 2]
a[0, 2]
np1 = np.arange(1., 5.)
np1.dtype


dtype('float64')

In [63]:
torch.tensor(np1).to(torch.float32).dtype

torch.float32

In [65]:
torch.manual_seed(42)
rand1 = torch.rand(3, 4)

torch.manual_seed(42)
rand2 = torch.rand(3, 4)
print(rand1)
print(rand2)

tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])
tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])
